"""add_saved_players_table

Revision ID: 66fc740e7b35
Revises: 690825fbda5a
Create Date: 2026-01-23 23:33:10.682487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66fc740e7b35'
down_revision: Union[str, None] = '690825fbda5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_players_id'), 'saved_players', ['id'], unique=False)
    op.create_index(op.f('ix_saved_players_user_id'), 'saved_players', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_players_user_id'), table_name='saved_players')
    op.drop_index(op.f('ix_saved_players_id'), table_name='saved_players')
    op.drop_table('saved_players')
    # ### end Alembic commands ###
