"""rename_cards_to_clash_royale_and_add_spy_cards

Revision ID: 6c7e8371b020
Revises: b7ec15ce7c28
Create Date: 2026-01-23 22:52:27.003887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7e8371b020'
down_revision: Union[str, None] = 'b7ec15ce7c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Переименовываем таблицу cards в clash_royale_cards
    op.rename_table('cards', 'clash_royale_cards')
    
    # Удаляем колонки image_path и image_path_evolution
    with op.batch_alter_table('clash_royale_cards', schema=None) as batch_op:
        batch_op.drop_column('image_path')
        batch_op.drop_column('image_path_evolution')
    
    # Создаем таблицу для карт шпиона
    op.create_table('spy_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('game_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spy_cards_id'), 'spy_cards', ['id'], unique=False)
    op.create_index(op.f('ix_spy_cards_name'), 'spy_cards', ['name'], unique=True)
    
    # Переносим карту "шпион" из clash_royale_cards в spy_cards
    op.execute("""
        INSERT INTO spy_cards (name, file_id, game_name, description, created_at, updated_at)
        SELECT name, file_id, NULL, 'Универсальная карта для игры в шпиона', created_at, updated_at
        FROM clash_royale_cards
        WHERE name = 'шпион'
    """)
    
    # Удаляем карту "шпион" из clash_royale_cards
    op.execute("DELETE FROM clash_royale_cards WHERE name = 'шпион'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(), nullable=False),
    sa.Column('image_path_evolution', sa.VARCHAR(), nullable=True),
    sa.Column('has_evolution', sa.BOOLEAN(), nullable=False),
    sa.Column('group', sa.VARCHAR(), nullable=False),
    sa.Column('elixir_cost', sa.INTEGER(), nullable=False),
    sa.Column('rarity', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('file_id', sa.VARCHAR(), nullable=True),
    sa.Column('file_id_evolution', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=1)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.drop_index(op.f('ix_spy_cards_name'), table_name='spy_cards')
    op.drop_index(op.f('ix_spy_cards_id'), table_name='spy_cards')
    op.drop_table('spy_cards')
    op.drop_index(op.f('ix_clash_royale_cards_name'), table_name='clash_royale_cards')
    op.drop_index(op.f('ix_clash_royale_cards_id'), table_name='clash_royale_cards')
    op.drop_table('clash_royale_cards')
    # ### end Alembic commands ###
