"""add_file_id_to_cards

Revision ID: b7ec15ce7c28
Revises: 9d1809f1d939
Create Date: 2026-01-23 22:42:36.124892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ec15ce7c28'
down_revision: Union[str, None] = '9d1809f1d939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('file_id', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('file_id_evolution', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'file_id_evolution')
    op.drop_column('cards', 'file_id')
    # ### end Alembic commands ###
